# Generated by Django 3.0.4 on 2020-04-30 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0004_auto_20200430_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexlimit',
            name='index_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_record', to='schPortal.Indexing'),
        ),
    ]
