# Generated by Django 3.0.4 on 2020-05-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0005_indexlimit_index_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexlimit',
            name='index_instance',
        ),
    ]
