# Generated by Django 3.0.4 on 2020-06-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0006_remove_indexlimit_index_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexlimit',
            name='used_limit',
        ),
    ]
