# Generated by Django 3.0.4 on 2020-06-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0007_remove_indexlimit_used_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexlimit',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
