# Generated by Django 3.0.4 on 2020-06-17 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
       ('adminPortal', '0008_indexlimit_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexlimit',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schPortal.School'),
        ),
    ]
