# Generated by Django 3.0.4 on 2020-06-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0009_auto_20200617_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexlimit',
            name='school',
            field=models.CharField(max_length=10),
        ),
    ]
