# Generated by Django 3.0.4 on 2020-06-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0010_auto_20200617_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='examLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=10)),
                ('assigned_limit', models.CharField(max_length=40)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
