# Generated by Django 4.2.6 on 2024-03-16 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profPortal', '0003_delete_professionalmodel'),
        ('adminPortal', '0014_alter_indexlimit_assigned_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='license',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('certificate', models.FileField(null=True, upload_to='images/license')),
            ],
        ),
        migrations.CreateModel(
            name='licenseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('certificate', models.FileField(null=True, upload_to='images/license')),
                ('prof', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='license', to='profPortal.professional')),
            ],
        ),
    ]
