# Generated by Django 4.2.6 on 2024-03-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0015_license_licensemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='license',
        ),
    ]
