# Generated by Django 4.2.6 on 2024-04-06 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminPortal', '0015_licensemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensemodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
