# Generated by Django 3.0.4 on 2020-04-14 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities_light', '0008_city_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_gov_area', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.Region')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_number', models.IntegerField(blank=True)),
                ('hod_name', models.CharField(blank=True, max_length=200)),
                ('hod_phone', models.IntegerField(blank=True)),
                ('hod_email', models.CharField(blank=True, max_length=100)),
                ('exam_quota_count', models.IntegerField()),
                ('index_quota_limit', models.IntegerField()),
                ('indexed', models.IntegerField()),
                ('exam_quota_limit', models.IntegerField()),
                ('exam_quota_used', models.IntegerField()),
                ('updated', models.BooleanField(default=False)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.Country')),
                ('lga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schPortal.LGA')),
                ('state', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
