# Generated by Django 3.0.4 on 2021-03-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0003_auto_20210323_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
