# Generated by Django 4.2.6 on 2023-11-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0009_remove_indexing_admission_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexing',
            name='qualifications',
        ),
    ]
