# Generated by Django 4.2.6 on 2023-11-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0010_remove_indexing_qualifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examregistration',
            old_name='institution_attended1',
            new_name='institutions_attended',
        ),
        migrations.RenameField(
            model_name='examregistration',
            old_name='prof_qualification1',
            new_name='professional_qualifications',
        ),
        migrations.RemoveField(
            model_name='examregistration',
            name='institution_attended2',
        ),
        migrations.RemoveField(
            model_name='examregistration',
            name='institution_attended3',
        ),
        migrations.RemoveField(
            model_name='examregistration',
            name='institution_attended4',
        ),
        migrations.RemoveField(
            model_name='examregistration',
            name='prof_qualification2',
        ),
        migrations.RemoveField(
            model_name='examregistration',
            name='prof_qualification3',
        ),
        migrations.RemoveField(
            model_name='examregistration',
            name='prof_qualification4',
        ),
        migrations.RemoveField(
            model_name='examregistration',
            name='qualification1',
        ),
        migrations.RemoveField(
            model_name='examregistration',
            name='qualification2',
        ),
        migrations.RemoveField(
            model_name='examregistration',
            name='qualification3',
        ),
        migrations.RemoveField(
            model_name='examregistration',
            name='qualification4',
        ),
        migrations.RemoveField(
            model_name='examregistration',
            name='referee_email1',
        ),
        migrations.RemoveField(
            model_name='examregistration',
            name='referee_email2',
        ),
        migrations.RemoveField(
            model_name='examregistration',
            name='referee_name1',
        ),
        migrations.RemoveField(
            model_name='examregistration',
            name='referee_name2',
        ),
        migrations.RemoveField(
            model_name='examregistration',
            name='referee_phone1',
        ),
        migrations.RemoveField(
            model_name='examregistration',
            name='referee_phone2',
        ),
        migrations.AddField(
            model_name='examregistration',
            name='qualifications',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='referees',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
