# Generated by Django 4.2.6 on 2023-11-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0011_rename_institution_attended1_examregistration_institutions_attended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexing',
            name='grades',
            field=models.TextField(blank=True, null=True),
        ),
    ]
