# Generated by Django 4.2.6 on 2023-11-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0013_rename_referees_indexing_admission_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examregistration',
            name='office_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='office_lga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='office_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='residential_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='residential_lga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='residential_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
