# Generated by Django 4.2.6 on 2023-11-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0014_alter_examregistration_office_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examregistration',
            name='state',
        ),
    ]
