# Generated by Django 4.2.6 on 2023-12-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0017_rename_examin_number_indexing_exam_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examregistration',
            old_name='declined',
            new_name='unapproved',
        ),
    ]
