# Generated by Django 4.2.6 on 2024-01-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0018_rename_declined_examregistration_unapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexing',
            name='lga',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
