# Generated by Django 4.2.6 on 2024-01-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0020_rename_o_level_cert_1_indexing_o_level_cert_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexing',
            old_name='referee_phone',
            new_name='referee_number',
        ),
        migrations.RenameField(
            model_name='indexing',
            old_name='referee_phone_2',
            new_name='referee_number_1',
        ),
    ]
