# Generated by Django 4.2.6 on 2024-01-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schPortal', '0021_rename_referee_phone_indexing_referee_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexing',
            old_name='referee_address_1',
            new_name='referee_address_2',
        ),
    ]
