# Generated by Django 3.0.4 on 2020-04-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200409_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_professional',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_school',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
