# Generated by Django 3.0.4 on 2020-04-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20200409_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sch_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
