# Generated by Django 3.0.4 on 2020-04-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20200414_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_update',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
