# Generated by Django 3.0.4 on 2020-04-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_profile_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sch_code',
            new_name='code',
        ),
    ]
