# Generated by Django 3.0.4 on 2020-04-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20200430_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='block',
        ),
        migrations.RemoveField(
            model_name='user',
            name='suspend',
        ),
    ]
