# Generated by Django 3.0.4 on 2020-05-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20200430_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school_logo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
