# Generated by Django 3.0.4 on 2020-05-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_ticket_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_id',
            field=models.IntegerField(null=True),
        ),
    ]
