# Generated by Django 3.0.4 on 2020-05-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_ticket_ticket_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='attachments',
            new_name='attachment1',
        ),
        migrations.AddField(
            model_name='ticket',
            name='attachment2',
            field=models.FileField(blank=True, null=True, upload_to='images/ticket_attachments'),
        ),
    ]
