# Generated by Django 3.0.4 on 2020-05-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_auto_20200516_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
