# Generated by Django 3.0.4 on 2020-05-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_auto_20200516_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='first_created',
            field=models.BooleanField(default=False),
        ),
    ]
