# Generated by Django 3.0.4 on 2020-05-16 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_ticket_first_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment1', models.FileField(blank=True, null=True, upload_to='images/ticket_attachments')),
                ('attachment2', models.FileField(blank=True, null=True, upload_to='images/ticket_attachments')),
                ('message', models.CharField(max_length=500)),
                ('ticket_status', models.CharField(max_length=20)),
                ('parent_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_ticket', to='authentication.Ticket')),
            ],
        ),
    ]
