# Generated by Django 3.0.4 on 2020-05-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_subticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
