# Generated by Django 3.0.4 on 2020-05-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ticket_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
