# Generated by Django 3.0.4 on 2020-05-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_ticket_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalcode',
            name='cadre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
