# Generated by Django 3.0.4 on 2020-06-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_auto_20200601_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
