# Generated by Django 4.2.6 on 2024-03-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0035_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalcode',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
