# Generated by Django 4.2.6 on 2024-03-28 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0038_alter_professionalcode_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Professional',
        ),
    ]
