# Generated by Django 4.2.6 on 2024-03-28 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0041_user_middle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionalcode',
            old_name='surname',
            new_name='last_name',
        ),
    ]
