# Generated by Django 4.2.6 on 2024-03-16 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profPortal', '0002_professional'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfessionalModel',
        ),
    ]
