# Generated by Django 4.2.6 on 2024-04-04 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profPortal', '0002_professional_delete_professionalmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfessionalModel',
        ),
    ]
