# Generated by Django 4.2.6 on 2024-03-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profPortal', '0003_delete_professionalmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional',
            old_name='prof_qualification1',
            new_name='institution_1',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='prof_qualification2',
            new_name='institution_2',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='prof_qualification3',
            new_name='institution_3',
        ),
        migrations.RenameField(
            model_name='professional',
            old_name='prof_qualification4',
            new_name='institution_4',
        ),
    ]
