# Generated by Django 4.2.6 on 2024-06-30 22:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profPortal', '0005_alter_licensereceipt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensereceipt',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='licensereceipt',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='licensereceipt',
            name='status',
            field=models.BooleanField(max_length=50),
        ),
    ]
