# Generated by Django 4.2.6 on 2024-06-30 22:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profPortal', '0006_licensereceipt_reference_alter_licensereceipt_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensereceipt',
            name='reference',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=250),
        ),
    ]
