# Generated by Django 4.2.6 on 2024-07-08 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profPortal', '0009_alter_licensereceipt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensereceipt',
            name='profuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_receipt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='licensereceipt',
            name='status',
            field=models.CharField(default='Pending Review', max_length=50),
        ),
    ]
