# Generated by Django 4.2.6 on 2024-07-08 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profPortal', '0010_alter_licensereceipt_profuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=uuid.uuid4, editable=False, max_length=250)),
                ('status', models.CharField(default='Pending Review', max_length=50)),
                ('remita_number', models.CharField(blank=True, max_length=100, null=True)),
                ('license_proof', models.FileField(null=True, upload_to='images/license')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('profuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
