# Generated by Django 3.0.4 on 2020-06-02 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
        ('cities_light', '0008_city_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/professional/prof_profile_img')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('surname', models.CharField(blank=True, max_length=200, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('telephone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('postal_address', models.CharField(blank=True, max_length=200, null=True)),
                ('religion', models.CharField(blank=True, max_length=200, null=True)),
                ('residential_address', models.CharField(blank=True, max_length=200, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=200, null=True)),
                ('maiden_name', models.CharField(blank=True, max_length=200, null=True)),
                ('senatorial_district', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=30, null=True)),
                ('qualification1', models.CharField(blank=True, max_length=200, null=True)),
                ('qualification2', models.CharField(blank=True, max_length=200, null=True)),
                ('qualification3', models.CharField(blank=True, max_length=200, null=True)),
                ('qualification4', models.CharField(blank=True, max_length=200, null=True)),
                ('prof_qualification1', models.CharField(blank=True, max_length=200, null=True)),
                ('prof_qualification2', models.CharField(blank=True, max_length=200, null=True)),
                ('prof_qualification3', models.CharField(blank=True, max_length=200, null=True)),
                ('prof_qualification4', models.CharField(blank=True, max_length=200, null=True)),
                ('employment_status', models.BooleanField(blank=True, null=True)),
                ('present_position', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('office_name', models.CharField(blank=True, max_length=100, null=True)),
                ('office_address', models.CharField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('office_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('office_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('updated', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('lga_of_birth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prof_lga_of_birth', to='schPortal.LGA')),
                ('lga_of_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prof_lgaOrigin', to='schPortal.LGA')),
                ('lga_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prof_lga_state', to='schPortal.LGA')),
                ('office_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prof_officeCountry', to='cities_light.Country')),
                ('office_lga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prof_officeLga', to='schPortal.LGA')),
                ('office_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prof_officeState', to='cities_light.Region')),
                ('profuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profuser', to=settings.AUTH_USER_MODEL)),
                ('residential_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.Country')),
                ('residential_lga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schPortal.LGA')),
                ('residential_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prof_residential_state', to='cities_light.Region')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.Region')),
                ('state_of_birth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prof_state_of_birth', to='cities_light.Region')),
                ('state_of_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prof_state_of_origin', to='cities_light.Region')),
            ],
        ),
    ]
