# Generated by Django 3.0.4 on 2020-06-02 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='employment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
