# Generated by Django 3.0.4 on 2022-07-05 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('schPortal', '0001_initial'),
        ('profPortal', '0002_auto_20200602_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='lga_of_birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prof_lga_of_birth_new', to='schPortal.LGA'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='lga_of_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prof_lgaOrigin_new', to='schPortal.LGA'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='lga_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prof_lga_state_new', to='schPortal.LGA'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='office_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prof_officeCountry_new', to='cities_light.Country'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='office_lga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prof_officeLga_new', to='schPortal.LGA'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='office_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prof_officeState_new', to='cities_light.Region'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='residential_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prof_residential_state_new', to='cities_light.Region'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='state_of_birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prof_state_of_birth_new', to='cities_light.Region'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='state_of_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prof_state_of_origin_new', to='cities_light.Region'),
        ),
    ]
